# Generated by Django 5.1.12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0031_alter_project_show_ground_truth_first"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="title",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Project name. Must be between 3 and 100 characters long.",
                max_length=100,
                null=True,
                validators=[
                    django.core.validators.MinLengthValidator(3),
                    django.core.validators.MaxLengthValidator(100),
                ],
                verbose_name="title",
            ),
        ),
    ]

